#
# ref: https://github.com/serverless/serverless/pull/6293
#
cors:
  handler: ${self:custom.path.app}/handlers/cors.handler
  description: Response to CORS pre-flight request
  timeout: 5
  reservedConcurrency: 1
  events:
    - alb:
        listenerArn:
          Ref: HTTPListener
        priority: 1
        conditions:
          path: '/*'
          method: ['OPTIONS']
