ping:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test
  timeout: 5
  reservedConcurrency: 1
  events:
    - http:
        path: ping
        method: get
        private: false
        cors: ${self:custom.http.cors}

pingAuth:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test with authentication
  timeout: 5
  reservedConcurrency: 1
  events:
    - http:
        path: ping/auth
        method: get
        private: true
        cors: ${self:custom.http.cors}

healthcheck:
  handler: ${self:custom.path.app}/handlers/healthcheck.handler
  description: ALB health check
  timeout: 5
  reservedConcurrency: 1
  events:
    - alb:
        listenerArn:
          Ref: HTTPListener
        priority: 97
        conditions:
          path: /healthcheck

albping:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping test from ALB
  timeout: 5
  reservedConcurrency: 1
  events:
    - alb:
        listenerArn:
          Ref: HTTPListener
        priority: 2
        conditions:
          path: ['/ping']
          method: ['GET']

albPingAuth:
  handler: ${self:custom.path.app}/handlers/ping.handler
  description: Ping Auth test from ALB
  timeout: 5
  reservedConcurrency: 1
  events:
    - alb:
        listenerArn:
          Ref: HTTPListener
        priority: 3
        apiKey:
          - ${env:AWS_ALB_API_KEY}
        conditions:
          path: ['/ping/auth']
          method: ['GET', 'POST']
        actions:  # optional
          - Type: 'fixed-response'
            FixedResponseConfig:
              StatusCode: 403
              ContentType: 'application/json'
              MessageBody: '{ "message": "Forbidden" }'
