#
# Resource file to create Application Load Balancer includes
# security group, target groups
# Application is sitting in vpc created in vpc.yml
#
# @ref https://github.com/pharindoko/serverless-load-balancer/blob/master/serverless.yml
#
# Alternative way to avoid cors on ALB
# https://geeks.uniplaces.com/avoid-pre-flight-requests-with-aws-application-load-balancer-f8cc5198b2bd
#

Resources:
  LoadBalancer:
    Type: 'AWS::ElasticLoadBalancingV2::LoadBalancer'
    Properties:
      Type: 'application'
      Name: ${self:service}
      IpAddressType: 'ipv4'
      Scheme: 'internet-facing'
      LoadBalancerAttributes:
        - { Key: 'deletion_protection.enabled', Value: false }
        - { Key: 'routing.http2.enabled', Value: false }
        - { Key: 'access_logs.s3.enabled', Value: false }
      SecurityGroups:
        - { Ref: SecurityGroup }
      # Subnet has to be public for internet facing ALB
      Subnets:
        - { Ref: PublicSubnet1 }
        - { Ref: PublicSubnet2 }
  HTTPListener:
    Type: 'AWS::ElasticLoadBalancingV2::Listener'
    Properties:
      LoadBalancerArn: { Ref: LoadBalancer }
      Port: 80
      Protocol: 'HTTP'
      DefaultActions:
        - Type: 'fixed-response'
          Order: 1
          FixedResponseConfig:
            StatusCode: 404
            ContentType: 'application/json'
            MessageBody: '{ "not": "found" }'
