Resources:
  Vpc:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: 10.0.0.0/16

  PrivateSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ${env:VPC_PRIVATE_SUBNET_1_AZ}
      CidrBlock: 10.0.1.0/24
      VpcId:
        Ref: Vpc
  PrivateSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ${env:VPC_PRIVATE_SUBNET_2_AZ}
      CidrBlock: 10.0.2.0/24
      VpcId:
        Ref: Vpc

  PublicSubnet1:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ${env:VPC_PUBLIC_SUBNET_1_AZ}
      CidrBlock: 10.0.21.0/24
      VpcId:
        Ref: Vpc
  PublicSubnet2:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: ${env:VPC_PUBLIC_SUBNET_2_AZ}
      CidrBlock: 10.0.22.0/24
      VpcId:
        Ref: Vpc
